Task 11
UA-AndriiZuiev/Hillel_AutomationTests pull request #2
Opened 2023-02-10 21:40 UTC by UA-AndriiZuiev

Homework 12

2023-02-11 12:49 UTC, Vladyslavtovkun requested changes

2023-02-11 12:49 UTC, Vladyslavtovkun commented on src/test/java/Test_HillelUa.java
> +        if (textHead.isDisplayed()) {
If else не потрібні, помилки і так будуть відображені в консолі

2023-02-11 12:49 UTC, Vladyslavtovkun commented on src/main/java/com/hillel/homework_11/util/WaitUtils.java
> +    public static void WaitUtilsIsVisible(WebDriver driver, WebElement element, String text) {
перейменуйте метод бо назва  WaitUtilsIsVisible, а чекає він поки не з'явиться текст.
І методи пишуться з маленької букви

2023-02-11 14:25 UTC, UA-AndriiZuiev commented on src/test/java/Test_HillelUa.java
> +        if (textHead.isDisplayed()) {
Видалив

2023-02-11 14:25 UTC, UA-AndriiZuiev commented on src/main/java/com/hillel/homework_11/util/WaitUtils.java
> +    public static void WaitUtilsIsVisible(WebDriver driver, WebElement element, String text) {
Переімнував обидва методи

2023-02-12 14:48 UTC, Vladyslavtovkun requested changes

2023-02-12 14:48 UTC, Vladyslavtovkun commented on src/main/java/com/hillel/homework_11/util/WaitUtils.java
> +    public static void waitUtilsIsDisplayed(WebDriver driver, WebElement element, String text) {
Перейменувати метод

2023-02-12 15:39 UTC, Vladyslavtovkun approved these changes

2023-02-12 15:44 UTC, merged